package fun.miranda.utils;

public class Strings {
    public static String CardNotFound = "§c角色不存在";
    public static String PCGetUsage = "§e用法:\n    §b/pcget §6<card> <key> §e获取角色的指定数值";
    public static String COCUsage = "§e用法:\n    §b/coc §6game <start|stop> §e控制游戏流程\n    §b/coc §6setkp <player> §e设置 KP\n    §b/coc §6setplayer <player> <card> §e设置玩家使用的卡\n    §b/coc §6reset §e重置所有角色和 KP";
    public static String KeyNotFound = "§c找不到属性§b%s";
    public static String CharResult = "§e角色§b%s§e的§b%s§e为§b%d";
    public static String PlayerNotFound = "§c玩家不在线或不存在";
    public static String NotOP = "§c你没有权限";
    public static String SetKP = "§e将§b%s§e设置为了KP";
    public static String SetPlayer = "§e将角色§b%s§e分配给了玩家§b%s";
    public static String Reset = "§e重置了所有角色和KP";
    public static String Success = "成功";
    public static String HardSuccess = "困难成功";
    public static String VeryHardSuccess = "极难成功";
    public static String BigSuccess = "大成功";
    public static String Fail = "失败";
    public static String BigFail = "大失败";
    public static String RDWithCheck1D = "§e玩家§b%s§e检定§d%s=>%d§e 结果: §a%d §6%s";
    public static String RDWithCheck = "§e玩家§b%s§e检定§d%s=>%d§e 结果: §a%s=%d §6%s";
    public static String RD1D = "§e玩家§b%s§d%s§e 结果: §a%d";
    public static String RD = "§e玩家§b%s§d%s§e 结果: §a%s=%d";
    public static String RA = "§e玩家§b%s§e检定§d%s(%d)§e 结果: §a%d §6%s";
    public static String EmptyResponse = "";
    public static String RH = "§e你暗骰检定§b%s§e的§d%s(%d) §e结果: §a%d §6%s";
    public static String RHLog = "§b%s§b暗骰检定§b%s§e的§d%s(%d) §e结果: §a%d §6%s";
    public static String RHShowKP = "§eKP§b%s§e进行了一次暗骰";
    public static String RHShowPlayer = "§e玩家§b%s§e进行了一次暗骰";
    public static String PCSetUsage = "§e用法:\n    §b/pcset §6<card> <key> <value> §e设置角色的指定数值";
    public static String PCSetAdd = "§e角色§b%s§e的§d%s§d§e增加了§b%s §e现在为§b%d";
    public static String PCSetSub = "§e角色§b%s§e的§d%s§d§e减少了§b%s §e现在为§b%d";
    public static String PCSetAdjust = "§e角色§b%s§e的§d%s§d§e调整为§b%d";
    public static String SCBigSuccess = "§e玩家§b%s§e检定§dSC §6大成功(%d) §e不扣除理智值";
    public static String SCBigFail = "§e玩家§b%s§e检定§dSC §6大失败(%d) §e最大程度扣除理智值§b%d §e附加症状: §6%s";
    public static String SCResultWithResist = "§e玩家§b%s§e检定§dSC(%d=>%d) §6%s\n§e本该扣除理智值 §b%s=%d §e由于精神固化改为扣除 §b%d\n§e剩余理智值 §b%d §e附加症状: §b%s";
    public static String SCResult = "§e玩家§b%s§e检定§dSC(%d=>%d) §6%s\n§e扣除理智值 §b%s=%d §e剩余理智值 §b%d §e附加症状: §b%s";
    public static String SAN = "理智值";
    public static String CrazyForever = "永久疯狂";
    public static String CrazyUncertainty = "不定性疯狂";
    public static String CrazyTemporary = "临时疯狂";
    public static String CrazyNo = "无";
    public static String CthulhuMyth = "克苏鲁神话";
    public static String Splitter = "------------------------------------";
    public static String Start = String.format("§d%s§e跑团开始§d%s", Splitter, Splitter);
    public static String Stop = String.format("§d%s§e跑团结束§d%s", Splitter, Splitter);
    public static String ShowStatus = String.format("§b%s§e状态§b%s\n", Splitter, Splitter);
    public static String ShowAttrs = String.format("§b%s§e属性§b%s\n", Splitter, Splitter);
    public static String ShowSkills = String.format("§b%s§e技能§b-%s\n", Splitter, Splitter);
    public static String ShowCharName = "§e角色: §b%s\n";
    public static String ShowStatusString = "§e生命值: §b%d§e/§b%d    §e魔法值: §b%d§e/§b%d    §e理智值: §b%d\n";
    public static String ShowAttrAndSkillString = "§e%s: §b%d      ";
    public static String HP = "生命值";
    public static String maxHP = "最大生命值";
    public static String MP = "魔法值";
    public static String maxMP = "最大魔法值";
    public static String PCShowUsage = "§e用法:\n    §b/pcshow §6<card> §e查看角色完整数据";
    public static String Enable = "§e[COC] §b启用";
    public static String Disable = "§e[COC] §b禁用";
    public static String NotStart = "§c跑团并没有开始";
}
